"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL??"http://127.0.0.1:8000";
const TOKEN_KEY="ow_token",ALERTS_KEY="ow_alerts";
type Tab="roadmap"|"levels"|"flow"|"alerts";
type Alert={id:string,type:"above"|"below",price:number,enabled:boolean,fired:boolean};
const fmt=(v:any)=>{if(typeof v!=="number")return v??"—";const a=Math.abs(v);return a>=1e9?`${(v/1e9).toFixed(2)}B`:a>=1e6?`${(v/1e6).toFixed(2)}M`:a>=1e3?`${(v/1e3).toFixed(1)}K`:v.toFixed(2)};
export default function Home(){
 const[token,setToken]=useState("");const[code,setCode]=useState("");const[data,setData]=useState<any>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(false);const[tab,setTab]=useState<Tab>("roadmap");const[symbol,setSymbol]=useState("SPY");const[alerts,setAlerts]=useState<Alert[]>([]);const[price,setPrice]=useState("");const[kind,setKind]=useState<"above"|"below">("above");
 useEffect(()=>{setToken(localStorage.getItem(TOKEN_KEY)??"");try{setAlerts(JSON.parse(localStorage.getItem(ALERTS_KEY)??"[]"))}catch{}},[]);
 useEffect(()=>{localStorage.setItem(ALERTS_KEY,JSON.stringify(alerts))},[alerts]);
 const login=async(e:FormEvent)=>{e.preventDefault();setError("");const r=await fetch(`${API}/api/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({access_code:code})});if(!r.ok){setError("Invalid access code");return}const p=await r.json();localStorage.setItem(TOKEN_KEY,p.token);setToken(p.token)};
 const logout=()=>{localStorage.removeItem(TOKEN_KEY);setToken("");setData(null)};
 const load=useCallback(async()=>{if(!token)return;setLoading(true);setError("");try{const r=await fetch(`${API}/api/roadmap/${symbol}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(r.status===401){logout();throw new Error("Session expired")}if(!r.ok)throw new Error(`API ${r.status}`);setData(await r.json())}catch(e){setError(e instanceof Error?e.message:"Connection failed")}finally{setLoading(false)}},[symbol,token]);
 useEffect(()=>{if(!token)return;load();const id=setInterval(load,120000);return()=>clearInterval(id)},[load,token]);
 useEffect(()=>{if(!data)return;const next=alerts.map(a=>{if(!a.enabled||a.fired)return a;const hit=a.type==="above"?data.spot>=a.price:data.spot<=a.price;if(!hit)return a;if("Notification" in window&&Notification.permission==="granted")new Notification(`${data.symbol} alert`,{body:`Price is ${a.type} ${a.price.toFixed(2)}. Current ${data.spot.toFixed(2)}`});return{...a,fired:true}});if(JSON.stringify(next)!==JSON.stringify(alerts))setAlerts(next)},[data,alerts]);
 const flow=useMemo(()=>data?[...data.flow].sort((a:any,b:any)=>Math.abs(b.volume_diff)-Math.abs(a.volume_diff)):[],[data]);
 const addAlert=()=>{const p=Number(price);if(!p)return;setAlerts([...alerts,{id:crypto.randomUUID(),type:kind,price:p,enabled:true,fired:false}]);setPrice("")};
 if(!token)return <main className="center"><form className="loginCard" onSubmit={login}><span className="brandMark large">OW</span><h1>Options Workstation</h1><p>Private personal access</p><input type="password" placeholder="Access code" value={code} onChange={e=>setCode(e.target.value)}/>{error&&<div className="formError">{error}</div>}<button className="primary">Open workstation</button></form></main>;
 if(!data)return <main className="center"><div className="loader"/><h1>Loading Trade GPS</h1><p>{error||"Building the live roadmap…"}</p><button className="primary" onClick={load}>Retry</button></main>;
 return <main><header className="topbar"><div className="brand"><span className="brandMark">OW</span><div><h1>Options Workstation</h1><p>Personal Trade GPS</p></div></div><div className="headerActions"><select value={symbol} onChange={e=>setSymbol(e.target.value)}><option>SPY</option><option>QQQ</option><option>IWM</option></select><button className="primary compact" onClick={load}>{loading?"…":"↻"}</button><button className="ghost compact" onClick={logout}>Exit</button></div></header>
 {!data.is_live&&<div className="warningBanner">Live data unavailable. Do not use fallback values for trading.</div>}
 <section className="hero"><div><span className="symbol">{data.symbol}</span><strong className="spot">${Number(data.spot).toFixed(2)}</strong><p>{data.bias}</p></div><div className="score"><strong>{data.conviction}</strong><span>conviction</span></div></section>
 <nav className="tabs">{(["roadmap","levels","flow","alerts"] as Tab[]).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav>
 {tab==="roadmap"&&<><section className="metrics"><article><span>Regime</span><strong>{data.regime}</strong><small>{data.source}</small></article><article><span>Expected Low</span><strong>${Number(data.expected_move.low).toFixed(2)}</strong></article><article><span>Expected High</span><strong>${Number(data.expected_move.high).toFixed(2)}</strong></article><article><span>Updated</span><strong>{new Date(data.updated_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</strong></article></section><section className="panel briefing"><div className="sectionTitle"><span>◈</span><h2>Trade GPS briefing</h2></div><p>{data.briefing}</p></section><section><div className="sectionTitle"><span>⇢</span><h2>Scenario roadmap</h2></div><div className="scenarioGrid">{data.scenarios.map((s:any)=><article className={`scenario ${s.direction}`} key={s.id}><div className="scenarioHead"><div><span>{s.status}</span><h3>{s.name}</h3></div><b>{s.conviction}</b></div><div className="trigger"><span>Activation trigger</span><p>{s.trigger}</p></div><div className="targets"><div><span>Target 1</span><strong>${Number(s.target1).toFixed(2)}</strong></div><div><span>Target 2</span><strong>{s.target2?`$${Number(s.target2).toFixed(2)}`:"—"}</strong></div><div><span>Invalidation</span><strong>${Number(s.invalidation).toFixed(2)}</strong></div></div><div className="reasons">{s.reasons.map((x:string)=><p key={x}>✓ {x}</p>)}{s.cautions.map((x:string)=><p className="warning" key={x}>⚠ {x}</p>)}</div></article>)}</div></section></>}
 {tab==="levels"&&<section><div className="sectionTitle"><span>◎</span><h2>Institutional level map</h2></div><section className="metrics"><article><span>Net GEX</span><strong>{fmt(data.metrics.net_gex)}</strong></article><article><span>Net DEX</span><strong>{fmt(data.metrics.net_dex)}</strong></article><article><span>Put / Call OI</span><strong>{fmt(data.metrics.put_call_oi_ratio)}</strong></article><article><span>Put / Call Volume</span><strong>{fmt(data.metrics.put_call_volume_ratio)}</strong></article></section><div className="levels">{data.levels.map((l:any)=><article className="level" key={`${l.name}-${l.price}`}><div><strong>{l.name}</strong><span>{l.role} · {l.side} spot</span></div><b>${Number(l.price).toFixed(2)}</b><div className="bar"><i style={{width:`${l.strength}%`}}/></div></article>)}</div></section>}
 {tab==="flow"&&<section><div className="sectionTitle"><span>≋</span><h2>Flow and concentration</h2></div><section className="metrics"><article><span>Call OI centroid</span><strong>{fmt(data.metrics.call_oi_centroid)}</strong></article><article><span>Put OI centroid</span><strong>{fmt(data.metrics.put_oi_centroid)}</strong></article><article><span>Call volume centroid</span><strong>{fmt(data.metrics.call_volume_centroid)}</strong></article><article><span>Put volume centroid</span><strong>{fmt(data.metrics.put_volume_centroid)}</strong></article></section><div className="tableWrap"><table><thead><tr><th>Strike</th><th>Net GEX</th><th>Call OI</th><th>Put OI</th><th>Vol Diff</th></tr></thead><tbody>{flow.slice(0,24).map((r:any)=><tr key={r.strike}><td>${r.strike.toFixed(2)}</td><td>{fmt(r.net_gex)}</td><td>{fmt(r.call_oi)}</td><td>{fmt(r.put_oi)}</td><td className={r.volume_diff>=0?"positive":"negative"}>{fmt(r.volume_diff)}</td></tr>)}</tbody></table></div></section>}
 {tab==="alerts"&&<section><div className="sectionTitle"><span>◉</span><h2>Personal alerts</h2></div><div className="panel alertBuilder"><p>These notifications work while the app is open. Background push is the next build.</p><div className="alertForm"><select value={kind} onChange={e=>setKind(e.target.value as any)}><option value="above">Price above</option><option value="below">Price below</option></select><input inputMode="decimal" placeholder="Price" value={price} onChange={e=>setPrice(e.target.value)}/><button className="primary" onClick={addAlert}>Add alert</button></div><button className="ghost" onClick={()=>"Notification" in window&&Notification.requestPermission()}>Enable browser notifications</button></div><div className="alertList">{alerts.length===0&&<p className="muted">No alerts yet.</p>}{alerts.map(a=><article className="alertRow" key={a.id}><div><strong>{symbol} {a.type} {a.price.toFixed(2)}</strong><span>{a.fired?"Triggered":a.enabled?"Watching":"Paused"}</span></div><div className="rowActions"><button className="ghost compact" onClick={()=>setAlerts(alerts.map(x=>x.id===a.id?{...x,enabled:!x.enabled,fired:false}:x))}>{a.enabled?"Pause":"Enable"}</button><button className="danger compact" onClick={()=>setAlerts(alerts.filter(x=>x.id!==a.id))}>Delete</button></div></article>)}</div></section>}
 <section className="warnings">{data.warnings.map((w:string)=><p key={w}>• {w}</p>)}</section><footer>Personal research tool. Wait for confirmation and use defined risk.</footer></main>}
